### ISSUE TITLE
event is now unbound when the component is destroyed 

### ISSUE THREAD

**Issue by mkoryak** [aishiekara/angular2-floatthead#1]
https://github.com/aishiekara/angular2-floatthead/blob/a46e9168e89d0b4feb82b396f4c768df0d8d9870/floatthead.directive.ts#L20

I have never used angular2, but I assume things will blow up when the table is removed but the listener sticks around _forever_.

**Comment by aishiekara** [comment]
Thank you for raising an issue, forgot to remove the event listener.
